version: '3.7'

x-var: &common
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test

services:
    spider_node:
        container_name: spider_node
        build:
            context: .
            args:
                IMAGE_TAG: "${IMAGE_TAG}"
        image: "mariadb-spider:${IMAGE_TAG}"
        <<: *common
    data_node1:
        container_name: data_node1
        image: "mariadb:${IMAGE_TAG}"
        <<: *common
    data_node2:
        container_name: data_node2
        image: "mariadb:${IMAGE_TAG}"
        <<: *common
